language: ruby

sudo: false

services:
  - redis
  - memcached

addons:
  postgresql: 9.3
  artifacts:
    paths:
    - log/

cache:
  directories:
    - vendor/bundle

sudo: false

rvm:
  - "2.0"
  - "2.1"

matrix:
  fast_finish: true

before_install:
  - gem install bundler -v 1.9.0

install:
  - bundle _1.9.0_ install --jobs=3 --retry=3 --path=${BUNDLE_PATH:-vendor/bundle}

before_script:
  - redis-cli config set save ""
  - 'RAILS_ENV=test bundle exec rake db:create db:migrate --trace'

script:
  - ./build.sh
