language: ruby
rvm:
  - jruby-19mode
jdk:
  - oraclejdk7
  - openjdk6
env:
  - JRUBY_OPTS="--server -Xcext.enabled=false -Xcompile.invokedynamic=false"
matrix:
  allow_failures:
    - rvm: jruby-head
      jdk: openjdk6
    - rvm: jruby-head
      jdk: oraclejdk7
  include:
    - rvm: 1.9.3
      jdk:
    - rvm: jruby-head
      jdk: openjdk6
    - rvm: jruby-head
      jdk: oraclejdk7
before_script:
  - 'RAILS_ENV=test rake db:create db:schema:load --trace'
script:
  - './build.sh'
notifications:
  irc: "irc.freenode.org#travis"
