language: ruby
env:
  global:
    - RUBY_GC_MALLOC_LIMIT=90000000
    - RUBY_FREE_MIN=200000
services:
  - redis
rvm:
  - jruby-19mode
jdk:
  - oraclejdk7
  - openjdk6
matrix:
  include:
    - rvm: 1.9.3
      jdk:
    - rvm: 2.0.0
      jdk:
    - rvm: rbx-2.1.1
      jdk:
  allow_failures:
    - rvm: rbx-2.1.1
      jdk:
before_script:
  - sudo service mysql stop
  - redis-cli config set save ""
  - 'bundle exec rake db:create db:test:prepare --trace'
script:
  - './build.sh'
notifications:
  irc: "irc.freenode.org#travis"
