language: ruby
services:
  - redis
rvm:
  - jruby-19mode
jdk:
  - oraclejdk7
  - openjdk6
matrix:
  include:
    - rvm: 1.9.3
      jdk:
before_script:
  - sudo service mysql stop
  - redis-cli config set save ""
  - 'RAILS_ENV=test rake db:create db:schema:load --trace'
script:
  - './build.sh'
notifications:
  irc: "irc.freenode.org#travis"
