language: ruby

sudo: false

env:
  - JRUBY_OPTS="--dev -Xcext.enabled=false -Xcompile.invokedynamic=false -J-Xmx1g"

services:
  - redis

addons:
  postgresql: 9.3
  artifacts:
    paths:
    - coverage/
    - log/

cache: bundler

sudo: false

rvm:
  - jruby-1.7.16
  - jruby-head
  - "2.0"
  - "2.1"

jdk: oraclejdk7

matrix:
  fast_finish: true
  allow_failures:
    - rvm: jruby-head

before_install:
  - gem install bundler -v 1.9.0

install:
  # JRuby fails to resolve dependencies on newer bundler
  - bundle _1.9.0_ install --jobs=3 --retry=3 --path=${BUNDLE_PATH:-vendor/bundle}

before_script:
  - redis-cli config set save ""
  - 'RAILS_ENV=test bundle exec rake db:create db:migrate --trace'

script:
  - ./build.sh

notifications:
  irc: irc.freenode.org#travis
  campfire:
    rooms:
      - secure: "FYd2nZjSOnzG0PoCfQ4mHYgjdj6W1C8jLoM6j+OsiLFDo37ShIwuMDjXkBNurUYY1ZyGLPZFngiC4QDZCw1RwefqMukjMqMG4BMt5SV3PNnodrJqLYcT6UfbzwDx8KaoiqClwBHGChzKj+2LgGSwhXxDwO7MqX4snJHTOLAwNy4="
    template:
      - '%{repository}#%{build_number} (%{branch} - %{commit} : %{author}): %{message} (details: %{build_url}, changes: %{compare_url})'
