language: ruby
rvm:
  - 1.9.3
  - jruby-18mode
  - jruby-19mode
jdk:
  - oraclejdk7
  - openjdk6
env:
  - JRUBY_OPTS="--server -Xcext.enabled=false -Xcompile.invokedynamic=false"
matrix:
  allow_failures:
    - rvm: jruby-head
  include:
    - rvm: jruby-head
      env: JRUBY_OPTS="--server -Xcext.enabled=false -Xcompile.invokedynamic=false --1.9"
    - rvm: jruby-head
      env: JRUBY_OPTS="--server -Xcext.enabled=false -Xcompile.invokedynamic=false --1.8"
before_script:
  - 'RAILS_ENV=test rake db:create db:schema:load --trace'
notifications:
  irc: "irc.freenode.org#travis"
