language: ruby
env:
  global:
    - RUBY_GC_MALLOC_LIMIT=90000000
    - RUBY_FREE_MIN=200000
services:
  - redis
addons:
  postgresql: 9.3
rvm:
  - jruby-19mode
  - jruby-head
  - 1.9.3
  - 2.0.0
  - 2.1.0
  - rbx-2.1.1
jdk:
  - oraclejdk7
matrix:
  fast_finish: true
  allow_failures:
    - rvm: 2.1.0
    - rvm: rbx-2.1.1
    - rvm: jruby-head
before_script:
  - sudo service mysql stop
  - redis-cli config set save ""
  - 'RAILS_ENV=test rake db:create db:structure:load --trace'
script:
  - './build.sh'
notifications:
  irc: "irc.freenode.org#travis"
