defaults: &defaults
  adapter: postgresql
  encoding: unicode
  pool: 5
  min_messages: warning

development:
  <<: *defaults
  database: travis_development

production:
  <<: *defaults
  database: travis_production

test:
  <<: *defaults
  database: travis_test

